a=int(input("enter first number: "))
b=int(input("enter second number: "))
print("addition of a and b is:",a+b)
print("subtraction of a and b is:",a-b)
print("multiplication of a and b is:",a*b)
print("division of a and b is:",a/b)
print("remainder of a and b is:",a%b)
