x1=float(input("enter cooridnate 1: "))
x2=float(input("enter coordinate 2: "))
y1=float(input("enter coordinate 3: "))
y2=float(input("enter coordinate 4: "))
res=(((y2-y1)**2 + (x2-x1)**2)**0.5)
print("distance between two points is:",res)