num1=int(input("enter 1st no: "))
num2=int(input("enter 2nd no: "))
num3=int(input("enter 3rd no: "))
num4=int(input("enter 4th no: "))
num5=int(input("enter 5th no: "))
num6=int(input("enter 6th no: "))
num7=int(input("enter 7th no: "))
num8=int(input("enter 8th no: "))
s={num1,num2,num3,num4,num5,num6,num7,num8}
print(s)